import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useContext, useEffect, useState } from "react";

import { BooksContext } from "@/store/Books/BooksContext";
import { BookList } from "@/components/BookList";
import { CircularProgress } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { getBooks, loading } = useContext(BooksContext);
  const headerTitle = "Ejercicio desarrollo Doorvel – Dev Next.js";

  useEffect(() => {
    getBooks();
  }, [getBooks]);

  return (
    <>
      <Head>
        <title>{headerTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <h1>{headerTitle}</h1>
      </header>
      <main className={`${styles.main} ${inter.className}`}>
        <section className={styles.section}>
          {loading ? (
            <CircularProgress
              sx={{ position: "absolute", top: "15%", left: "48%" }}
            />
          ) : (
            <BookList />
          )}
        </section>
      </main>
    </>
  );
}
